// Generated by scripts/generate-doc-page-resources.mjs
// Do not edit manually.

export interface PageResourceEntry {
  routePath: string
  routeKey: string
  sectionKey: string
  resourceKey: string
}

export const PAGE_RESOURCE_ENTRIES: PageResourceEntry[] = [
  {
    "routePath": "/",
    "routeKey": "index",
    "sectionKey": "root",
    "resourceKey": "index"
  },
  {
    "routePath": "/adr/0001-shared-tube-rebuild",
    "routeKey": "adr/0001-shared-tube-rebuild",
    "sectionKey": "adr",
    "resourceKey": "adr__0001-shared-tube-rebuild"
  },
  {
    "routePath": "/ai-tools/assistant-protocols",
    "routeKey": "ai-tools/assistant-protocols",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/automation-policy",
    "routeKey": "ai-tools/assistant-protocols/automation-policy",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__automation-policy"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/backup-export-policy",
    "routeKey": "ai-tools/assistant-protocols/backup-export-policy",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__backup-export-policy"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/bilingual-strings",
    "routeKey": "ai-tools/assistant-protocols/bilingual-strings",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__bilingual-strings"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/brand-tokens-ui",
    "routeKey": "ai-tools/assistant-protocols/brand-tokens-ui",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__brand-tokens-ui"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/cleanup-refactor",
    "routeKey": "ai-tools/assistant-protocols/cleanup-refactor",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__cleanup-refactor"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/dependency-policy",
    "routeKey": "ai-tools/assistant-protocols/dependency-policy",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__dependency-policy"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/deployment-policy",
    "routeKey": "ai-tools/assistant-protocols/deployment-policy",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__deployment-policy"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/docs-standards",
    "routeKey": "ai-tools/assistant-protocols/docs-standards",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__docs-standards"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/file-changes",
    "routeKey": "ai-tools/assistant-protocols/file-changes",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__file-changes"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/git-branch-policy",
    "routeKey": "ai-tools/assistant-protocols/git-branch-policy",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__git-branch-policy"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/global-instruction-sync",
    "routeKey": "ai-tools/assistant-protocols/global-instruction-sync",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__global-instruction-sync"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/gui-verification",
    "routeKey": "ai-tools/assistant-protocols/gui-verification",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__gui-verification"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/handling-bugs",
    "routeKey": "ai-tools/assistant-protocols/handling-bugs",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__handling-bugs"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/incident-response",
    "routeKey": "ai-tools/assistant-protocols/incident-response",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__incident-response"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/knowledge-scout",
    "routeKey": "ai-tools/assistant-protocols/knowledge-scout",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__knowledge-scout"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/knowledge-sync",
    "routeKey": "ai-tools/assistant-protocols/knowledge-sync",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__knowledge-sync"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/legal-compliance",
    "routeKey": "ai-tools/assistant-protocols/legal-compliance",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__legal-compliance"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/long-running-tasks",
    "routeKey": "ai-tools/assistant-protocols/long-running-tasks",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__long-running-tasks"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/multi-agent-flow",
    "routeKey": "ai-tools/assistant-protocols/multi-agent-flow",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__multi-agent-flow"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/network-infrastructure",
    "routeKey": "ai-tools/assistant-protocols/network-infrastructure",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__network-infrastructure"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/pr-policy",
    "routeKey": "ai-tools/assistant-protocols/pr-policy",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__pr-policy"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/project-creation",
    "routeKey": "ai-tools/assistant-protocols/project-creation",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__project-creation"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/renaming",
    "routeKey": "ai-tools/assistant-protocols/renaming",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__renaming"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/request-rate-limiting",
    "routeKey": "ai-tools/assistant-protocols/request-rate-limiting",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__request-rate-limiting"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/secrets-handling",
    "routeKey": "ai-tools/assistant-protocols/secrets-handling",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__secrets-handling"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/security-posture",
    "routeKey": "ai-tools/assistant-protocols/security-posture",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__security-posture"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/skill-sync",
    "routeKey": "ai-tools/assistant-protocols/skill-sync",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__skill-sync"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/source-of-truth",
    "routeKey": "ai-tools/assistant-protocols/source-of-truth",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__source-of-truth"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/submodule-boundaries",
    "routeKey": "ai-tools/assistant-protocols/submodule-boundaries",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__submodule-boundaries"
  },
  {
    "routePath": "/ai-tools/assistant-protocols/verification",
    "routeKey": "ai-tools/assistant-protocols/verification",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__assistant-protocols__verification"
  },
  {
    "routePath": "/ai-tools/claude-code",
    "routeKey": "ai-tools/claude-code",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__claude-code"
  },
  {
    "routePath": "/ai-tools/cursor",
    "routeKey": "ai-tools/cursor",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__cursor"
  },
  {
    "routePath": "/ai-tools/windsurf",
    "routeKey": "ai-tools/windsurf",
    "sectionKey": "ai-tools",
    "resourceKey": "ai-tools__windsurf"
  },
  {
    "routePath": "/api-reference/authentication",
    "routeKey": "api-reference/authentication",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__authentication"
  },
  {
    "routePath": "/api-reference/endpoint/create",
    "routeKey": "api-reference/endpoint/create",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__endpoint__create"
  },
  {
    "routePath": "/api-reference/endpoint/delete",
    "routeKey": "api-reference/endpoint/delete",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__endpoint__delete"
  },
  {
    "routePath": "/api-reference/endpoint/get",
    "routeKey": "api-reference/endpoint/get",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__endpoint__get"
  },
  {
    "routePath": "/api-reference/endpoint/webhook",
    "routeKey": "api-reference/endpoint/webhook",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__endpoint__webhook"
  },
  {
    "routePath": "/api-reference/endpoints",
    "routeKey": "api-reference/endpoints",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__endpoints"
  },
  {
    "routePath": "/api-reference/introduction",
    "routeKey": "api-reference/introduction",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__introduction"
  },
  {
    "routePath": "/api-reference/sdk",
    "routeKey": "api-reference/sdk",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__sdk"
  },
  {
    "routePath": "/api-reference/webhooks",
    "routeKey": "api-reference/webhooks",
    "sectionKey": "api-reference",
    "resourceKey": "api-reference__webhooks"
  },
  {
    "routePath": "/branding",
    "routeKey": "branding",
    "sectionKey": "branding",
    "resourceKey": "branding"
  },
  {
    "routePath": "/compliance/data-residency",
    "routeKey": "compliance/data-residency",
    "sectionKey": "compliance",
    "resourceKey": "compliance__data-residency"
  },
  {
    "routePath": "/compliance/gdpr",
    "routeKey": "compliance/gdpr",
    "sectionKey": "compliance",
    "resourceKey": "compliance__gdpr"
  },
  {
    "routePath": "/compliance/hipaa",
    "routeKey": "compliance/hipaa",
    "sectionKey": "compliance",
    "resourceKey": "compliance__hipaa"
  },
  {
    "routePath": "/compliance/pci-dss",
    "routeKey": "compliance/pci-dss",
    "sectionKey": "compliance",
    "resourceKey": "compliance__pci-dss"
  },
  {
    "routePath": "/development",
    "routeKey": "development",
    "sectionKey": "development",
    "resourceKey": "development"
  },
  {
    "routePath": "/essentials/backup-strategy",
    "routeKey": "essentials/backup-strategy",
    "sectionKey": "essentials",
    "resourceKey": "essentials__backup-strategy"
  },
  {
    "routePath": "/essentials/code",
    "routeKey": "essentials/code",
    "sectionKey": "essentials",
    "resourceKey": "essentials__code"
  },
  {
    "routePath": "/essentials/images",
    "routeKey": "essentials/images",
    "sectionKey": "essentials",
    "resourceKey": "essentials__images"
  },
  {
    "routePath": "/essentials/large-files",
    "routeKey": "essentials/large-files",
    "sectionKey": "essentials",
    "resourceKey": "essentials__large-files"
  },
  {
    "routePath": "/essentials/markdown",
    "routeKey": "essentials/markdown",
    "sectionKey": "essentials",
    "resourceKey": "essentials__markdown"
  },
  {
    "routePath": "/essentials/navigation",
    "routeKey": "essentials/navigation",
    "sectionKey": "essentials",
    "resourceKey": "essentials__navigation"
  },
  {
    "routePath": "/essentials/project-tracking",
    "routeKey": "essentials/project-tracking",
    "sectionKey": "essentials",
    "resourceKey": "essentials__project-tracking"
  },
  {
    "routePath": "/essentials/reusable-snippets",
    "routeKey": "essentials/reusable-snippets",
    "sectionKey": "essentials",
    "resourceKey": "essentials__reusable-snippets"
  },
  {
    "routePath": "/essentials/settings",
    "routeKey": "essentials/settings",
    "sectionKey": "essentials",
    "resourceKey": "essentials__settings"
  },
  {
    "routePath": "/getting-started/daily-flows",
    "routeKey": "getting-started/daily-flows",
    "sectionKey": "getting-started",
    "resourceKey": "getting-started__daily-flows"
  },
  {
    "routePath": "/getting-started/overview",
    "routeKey": "getting-started/overview",
    "sectionKey": "getting-started",
    "resourceKey": "getting-started__overview"
  },
  {
    "routePath": "/getting-started/products-and-services",
    "routeKey": "getting-started/products-and-services",
    "sectionKey": "getting-started",
    "resourceKey": "getting-started__products-and-services"
  },
  {
    "routePath": "/getting-started/quick-installation",
    "routeKey": "getting-started/quick-installation",
    "sectionKey": "getting-started",
    "resourceKey": "getting-started__quick-installation"
  },
  {
    "routePath": "/getting-started/system-requirements",
    "routeKey": "getting-started/system-requirements",
    "sectionKey": "getting-started",
    "resourceKey": "getting-started__system-requirements"
  },
  {
    "routePath": "/guides/best-practices",
    "routeKey": "guides/best-practices",
    "sectionKey": "guides",
    "resourceKey": "guides__best-practices"
  },
  {
    "routePath": "/guides/daily-operations",
    "routeKey": "guides/daily-operations",
    "sectionKey": "guides",
    "resourceKey": "guides__daily-operations"
  },
  {
    "routePath": "/guides/maintenance",
    "routeKey": "guides/maintenance",
    "sectionKey": "guides",
    "resourceKey": "guides__maintenance"
  },
  {
    "routePath": "/guides/troubleshooting",
    "routeKey": "guides/troubleshooting",
    "sectionKey": "guides",
    "resourceKey": "guides__troubleshooting"
  },
  {
    "routePath": "/hardware/encrypted-storage",
    "routeKey": "hardware/encrypted-storage",
    "sectionKey": "hardware",
    "resourceKey": "hardware__encrypted-storage"
  },
  {
    "routePath": "/hardware/network-appliances",
    "routeKey": "hardware/network-appliances",
    "sectionKey": "hardware",
    "resourceKey": "hardware__network-appliances"
  },
  {
    "routePath": "/installation/hardware-installation",
    "routeKey": "installation/hardware-installation",
    "sectionKey": "installation",
    "resourceKey": "installation__hardware-installation"
  },
  {
    "routePath": "/installation/initial-configuration",
    "routeKey": "installation/initial-configuration",
    "sectionKey": "installation",
    "resourceKey": "installation__initial-configuration"
  },
  {
    "routePath": "/installation/integration-guides",
    "routeKey": "installation/integration-guides",
    "sectionKey": "installation",
    "resourceKey": "installation__integration-guides"
  },
  {
    "routePath": "/installation/software-deployment",
    "routeKey": "installation/software-deployment",
    "sectionKey": "installation",
    "resourceKey": "installation__software-deployment"
  },
  {
    "routePath": "/logs/ops-log-2026-05-13",
    "routeKey": "logs/ops-log-2026-05-13",
    "sectionKey": "logs",
    "resourceKey": "logs__ops-log-2026-05-13"
  },
  {
    "routePath": "/logs/ops-log-2026-05-21",
    "routeKey": "logs/ops-log-2026-05-21",
    "sectionKey": "logs",
    "resourceKey": "logs__ops-log-2026-05-21"
  },
  {
    "routePath": "/operations/agent-ledger-schema",
    "routeKey": "operations/agent-ledger-schema",
    "sectionKey": "operations",
    "resourceKey": "operations__agent-ledger-schema"
  },
  {
    "routePath": "/operations/backups",
    "routeKey": "operations/backups",
    "sectionKey": "operations",
    "resourceKey": "operations__backups"
  },
  {
    "routePath": "/operations/command-line-tool",
    "routeKey": "operations/command-line-tool",
    "sectionKey": "operations",
    "resourceKey": "operations__command-line-tool"
  },
  {
    "routePath": "/operations/deploy-alerts",
    "routeKey": "operations/deploy-alerts",
    "sectionKey": "operations",
    "resourceKey": "operations__deploy-alerts"
  },
  {
    "routePath": "/operations/deploy-status-api",
    "routeKey": "operations/deploy-status-api",
    "sectionKey": "operations",
    "resourceKey": "operations__deploy-status-api"
  },
  {
    "routePath": "/operations/deployment-flow",
    "routeKey": "operations/deployment-flow",
    "sectionKey": "operations",
    "resourceKey": "operations__deployment-flow"
  },
  {
    "routePath": "/operations/health-ledger",
    "routeKey": "operations/health-ledger",
    "sectionKey": "operations",
    "resourceKey": "operations__health-ledger"
  },
  {
    "routePath": "/operations/jira-sync",
    "routeKey": "operations/jira-sync",
    "sectionKey": "operations",
    "resourceKey": "operations__jira-sync"
  },
  {
    "routePath": "/operations/mcp-ledger-tools",
    "routeKey": "operations/mcp-ledger-tools",
    "sectionKey": "operations",
    "resourceKey": "operations__mcp-ledger-tools"
  },
  {
    "routePath": "/operations/network-map",
    "routeKey": "operations/network-map",
    "sectionKey": "operations",
    "resourceKey": "operations__network-map"
  },
  {
    "routePath": "/operations/project-bootstrap",
    "routeKey": "operations/project-bootstrap",
    "sectionKey": "operations",
    "resourceKey": "operations__project-bootstrap"
  },
  {
    "routePath": "/operations/residential-egress-proxy",
    "routeKey": "operations/residential-egress-proxy",
    "sectionKey": "operations",
    "resourceKey": "operations__residential-egress-proxy"
  },
  {
    "routePath": "/operations/secrets",
    "routeKey": "operations/secrets",
    "sectionKey": "operations",
    "resourceKey": "operations__secrets"
  },
  {
    "routePath": "/operations/services-inventory",
    "routeKey": "operations/services-inventory",
    "sectionKey": "operations",
    "resourceKey": "operations__services-inventory"
  },
  {
    "routePath": "/operations/tailscale",
    "routeKey": "operations/tailscale",
    "sectionKey": "operations",
    "resourceKey": "operations__tailscale"
  },
  {
    "routePath": "/operations/webhook-secret-rotation",
    "routeKey": "operations/webhook-secret-rotation",
    "sectionKey": "operations",
    "resourceKey": "operations__webhook-secret-rotation"
  },
  {
    "routePath": "/quickstart",
    "routeKey": "quickstart",
    "sectionKey": "quickstart",
    "resourceKey": "quickstart"
  },
  {
    "routePath": "/security/certifications",
    "routeKey": "security/certifications",
    "sectionKey": "security",
    "resourceKey": "security__certifications"
  },
  {
    "routePath": "/security/encryption-protocols",
    "routeKey": "security/encryption-protocols",
    "sectionKey": "security",
    "resourceKey": "security__encryption-protocols"
  },
  {
    "routePath": "/security/industry-standards",
    "routeKey": "security/industry-standards",
    "sectionKey": "security",
    "resourceKey": "security__industry-standards"
  },
  {
    "routePath": "/security/zero-knowledge-encryption-standard",
    "routeKey": "security/zero-knowledge-encryption-standard",
    "sectionKey": "security",
    "resourceKey": "security__zero-knowledge-encryption-standard"
  },
  {
    "routePath": "/software/access-control",
    "routeKey": "software/access-control",
    "sectionKey": "software",
    "resourceKey": "software__access-control"
  },
  {
    "routePath": "/software/backup-recovery",
    "routeKey": "software/backup-recovery",
    "sectionKey": "software",
    "resourceKey": "software__backup-recovery"
  },
  {
    "routePath": "/software/encryption-software",
    "routeKey": "software/encryption-software",
    "sectionKey": "software",
    "resourceKey": "software__encryption-software"
  },
  {
    "routePath": "/software/security-monitoring",
    "routeKey": "software/security-monitoring",
    "sectionKey": "software",
    "resourceKey": "software__security-monitoring"
  },
  {
    "routePath": "/software/vault-tv",
    "routeKey": "software/vault-tv",
    "sectionKey": "software",
    "resourceKey": "software__vault-tv"
  },
  {
    "routePath": "/support/contact",
    "routeKey": "support/contact",
    "sectionKey": "support",
    "resourceKey": "support__contact"
  },
  {
    "routePath": "/support/faq",
    "routeKey": "support/faq",
    "sectionKey": "support",
    "resourceKey": "support__faq"
  },
  {
    "routePath": "/support/rma",
    "routeKey": "support/rma",
    "sectionKey": "support",
    "resourceKey": "support__rma"
  },
  {
    "routePath": "/support/updates",
    "routeKey": "support/updates",
    "sectionKey": "support",
    "resourceKey": "support__updates"
  },
  {
    "routePath": "/support/warranty",
    "routeKey": "support/warranty",
    "sectionKey": "support",
    "resourceKey": "support__warranty"
  }
]
